### ISSUE TITLE
Error iptables v1.4.21: host/network  not found 

### ISSUE THREAD

**Issue by SUNFei1126** [MohithReddy2439/Proxifier-For-Linux#2]
when run  proxifier start 

iptables v1.4.21: host/network `p40.t.16yun.cnnProxyServerPort=6448nProxyServerAuthorization=***' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `p40.t.16yun.cnnProxyServerPort=6448nProxyServerAuthorization=***' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `p40.t.16yun.cnnProxyServerPort=6448nProxyServerAuthorization=***' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `p40.t.16yun.cnnProxyServerPort=6448nProxyServerAuthorization=***' not found
Try `iptables -h' or 'iptables --help' for more information.

**Comment by SUNFei1126** [comment]
I tried with IP adress  but is the same error    can you tell me where used iptables command

**Comment by MohithReddy2439** [comment]
That is not expected with IP address it should work  , error is iptablesis not able to resolve the proxy server address , Any how you are free to modify code , you can find iptables command in fakehttpserver and fakehttpsserver files , Go their and make some necessary modifications , If you find any

**Comment by MohithReddy2439** [comment]
![screenshot from 2018-06-12 17-02-04](https://user-images.githubusercontent.com/24791724/41287997-5f85a038-6e62-11e8-973f-072216e32e5d.png)
You can see the above image file there i gave some invalid server IP , iptables is not able to resolve that , and it flashed the same error as in your case

**Comment by SUNFei1126** [comment]
my proxy is http Tunnel proxy use with authentication usename:password   does it enable?

**Comment by MohithReddy2439** [comment]
Ha , For sure this application supports only HTTP Proxy.  The support for http  https is also added , ftp is not yet added
